import {Dimensions, StyleSheet} from 'react-native';
import {colors, fontFamily, fontSize, sizes} from '../../services';

export const styles = StyleSheet.create({
  container: {height: sizes.screenHeight, backgroundColor: colors.white},
  head: {
    textAlign: 'center',
    fontSize: fontSize.h5,
    color: colors.black,
    fontWeight: 'bold',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  center: {
    alignItems: 'center',
  },
  marginTop: {
    marginTop: sizes.screenHeight * 0.02,
    marginBottom: sizes.screenHeight * 0.015,
  },
  btnFilled: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.35,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledWorkout: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.5,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledGolf: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledSoccer: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.3,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledHockey: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.4,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnOutlined: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.35,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedWorkout: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.5,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedGolf: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedSoccer: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.3,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedHockey: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.4,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },

  top: {
    marginTop: sizes.screenHeight * 0.015,
  },
  btnTop: {
    marginTop: sizes.screenHeight * 0.05,
  },
  interestView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: sizes.screenWidth * 0.8,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  interestOption: {marginTop: sizes.screenHeight * 0.025},
  btnTextFilled: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,
    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
    paddingVertical: sizes.screenWidth * 0.02,
    paddingHorizontal: sizes.screenWidth * 0.07,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnTextFilledIOS: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,
    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
  },
  btnText: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,

    borderColor: colors.black,
    paddingVertical: sizes.screenWidth * 0.02,
    paddingHorizontal: sizes.screenWidth * 0.07,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnTextIOS: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,
    borderColor: colors.black,
  },
});
