import {Dimensions, StyleSheet} from 'react-native';
import {colors, fontFamily, fontSize, sizes} from '../../services';

export const styles = StyleSheet.create({
  container: {height: sizes.screenHeight, backgroundColor: colors.white},
  head: {
    textAlign: 'center',
    fontSize: fontSize.h5,
    color: colors.black,
    fontWeight: 'bold',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  center: {
    alignItems: 'center',
  },
  marginTop: {
    marginTop: sizes.screenHeight * 0.02,
    marginBottom: sizes.screenHeight * 0.015,
  },
  btnFilled: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.35,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledHairdresser: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.4,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledHairdresser2: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.42,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledDesigner: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.3,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledDesigner2: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.28,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnOutlined: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.35,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedDesigner: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.3,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedDesigner2: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.28,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedHairdresser: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.4,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedHairdresser2: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.42,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnText: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,
  },
  btnTextFilled: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,
  },
  btnFilledBook: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.4,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnOutlinedBook: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.4,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnFilledClub: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.3,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnOutlinedClub: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.3,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  top: {
    marginTop: sizes.screenHeight * 0.015,
  },
  btnTop: {
    marginTop: sizes.screenHeight * 0.04,
  },
  interestView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: sizes.screenWidth * 0.8,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  interestViewIOS:{
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  interestOption: {marginTop: sizes.screenHeight * 0.025},
  btnTextFilled: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,

    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
    paddingVertical: sizes.screenWidth * 0.02,
    paddingHorizontal: sizes.screenWidth * 0.07,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnText: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,
    borderColor: colors.black,
    paddingVertical: sizes.screenWidth * 0.02,
    paddingHorizontal: sizes.screenWidth * 0.07,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnTextFilledIOS: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,
    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
  },
  btnTextIOS: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,
    borderColor: colors.black,
  },
});
