import {Dimensions, StyleSheet} from 'react-native';
import {colors, fontFamily, fontSize, sizes} from '../../services';

export const styles = StyleSheet.create({
  container: {height: sizes.screenHeight, backgroundColor: colors.white},
  head: {
    textAlign: 'center',
    fontSize: fontSize.h3,
    color: colors.black,
    fontWeight: 'bold',
  },
  btnOutlined: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.35,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedDrink: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedArt: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedOthers: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedClub: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedBook: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedGame: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedAround: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnFilledBook: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnOutlinedChat: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedCooking: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnFilled: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.35,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledDrink: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledArt: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledOthers: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledClub: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledChat: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledCooking: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledGame: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledAround: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },

  btnTextFilled: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  center: {
    alignItems: 'center',
  },
  marginTop: {
    marginTop: sizes.screenHeight * 0.02,
    marginBottom: sizes.screenHeight * 0.015,
  },
  top: {
    marginTop: sizes.screenHeight * 0.015,
  },
  btnTop: {
    marginTop: sizes.screenHeight * 0.09,
  },
  right: {
    // marginLeft:sizes.screenWidth*0.03
  },
  interestView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: sizes.screenWidth * 0.8,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  interestOption: {marginTop: sizes.screenHeight * 0.025},
  btnTextFilled: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,

    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
    paddingVertical: sizes.screenWidth * 0.02,
    paddingHorizontal: sizes.screenWidth * 0.06,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnText: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,

    borderColor: colors.black,
    paddingVertical: sizes.screenWidth * 0.02,
    paddingHorizontal: sizes.screenWidth * 0.06,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnTextFilledIOS: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,
    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
  },
  btnTextIOS: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,
    borderColor: colors.black,
  },
  loader: {
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    padding: sizes.screenHeight * 0.02,
    width: sizes.screenWidth * 0.5,
    borderRadius: sizes.screenWidth * 0.03,
  },

  modalView: {
    backgroundColor: colors.white,
    height: sizes.screenHeight * 0.33,
    width: sizes.screenWidth * 0.7,
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: sizes.screenWidth * 0.06,
    justifyContent: 'center',
  },
  checkmark: {
    height: sizes.screenHeight * 0.04,
    width: sizes.screenHeight * 0.04,
    bottom: sizes.screenHeight * 0.05,
  },
  modelText: {
    fontSize: fontSize.medium,
    textAlign: 'center',
    color: colors.black,
    width: sizes.screenWidth * 0.45,
    fontWeight: '500',
    bottom: sizes.screenHeight * 0.03,
  },
  submitTopModal: {
    bottom: sizes.screenHeight * 0.1,
  },
  signInBtnModal: {
    height: sizes.screenHeight * 0.06,
    width: sizes.screenWidth * 0.4,
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    borderRadius: sizes.screenWidth * 0.02,
  },
  signInBtnModal: {
    height: sizes.screenHeight * 0.06,
    width: sizes.screenWidth * 0.4,
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    borderRadius: sizes.screenWidth * 0.02,
  },
  signUpContent: {
    paddingRight: sizes.screenWidth * 0.05,
    paddingLeft: sizes.screenWidth * 0.05,
  },
  
  btnText2: {
    textAlign: 'center',
    marginTop: sizes.screenHeight * 0.015,
    color: colors.black,
    fontWeight: '700',
    fontSize: fontSize.medium,
  },
  blueText2: {
    color: colors.appTextColor1,
    fontWeight: '800',
  },
  btnTextIOS2: {
    textAlign: 'center',
    marginTop: sizes.screenHeight * 0.018,
    color: colors.black,
    fontWeight: '700',
    fontSize: fontSize.medium,
  },
  bgImage: {
    height: sizes.screenHeight * 0.09,
    resizeMode: 'cover',
    width: sizes.screenWidth,
    marginBottom: sizes.screenHeight * -0.04,
  },
});
