import {Dimensions, StyleSheet} from 'react-native';
import {colors, fontFamily, fontSize, sizes} from '../../services';

export const styles = StyleSheet.create({
  container: {height: sizes.screenHeight, backgroundColor: colors.white},
  head: {
    textAlign: 'center',
    fontSize: fontSize.h5,
    color: colors.black,
    fontWeight: 'bold',
  },
  btnOutlined: {
    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
    padding: sizes.screenWidth * 0.02,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedArt: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedOthers: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedClub: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedBook: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedGame: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedAround: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.7,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnFilledBook: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnOutlinedChat: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnOutlinedCooking: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnFilled: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.35,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledArt: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.45,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledOthers: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledClub: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledChat: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledCooking: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.25,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledGame: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.2,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnFilledAround: {
    borderColor: colors.black,
    width: sizes.screenWidth * 0.7,
    padding: sizes.screenWidth * 0.02,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  btnText: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,

    borderColor: colors.black,
    paddingVertical: sizes.screenWidth * 0.02,
    paddingHorizontal: sizes.screenWidth * 0.07,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
  },
  btnTextFilled: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,

    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
    paddingVertical: sizes.screenWidth * 0.02,
    paddingHorizontal: sizes.screenWidth * 0.07,
    borderWidth: 1,
    borderRadius: sizes.screenWidth * 0.06,
    marginRight: sizes.screenHeight * 0.007,
    marginLeft: sizes.screenHeight * 0.007,
    backgroundColor: colors.appTextColor1,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  center: {
    alignItems: 'center',
  },
  marginTop: {
    marginTop: sizes.screenHeight * 0.02,
    marginBottom: sizes.screenHeight * 0.015,
  },
  top: {
    marginTop: sizes.screenHeight * 0.015,
  },
  btnTop: {
    marginTop: sizes.screenHeight * 0.06,
  },
  right: {
    // marginLeft:sizes.screenWidth*0.03
  },
  interestView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: sizes.screenWidth * 0.8,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  btnTextFilledIOS: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.black,
    borderColor: colors.black,
    // width: sizes.screenWidth * 0.35,
  },
  btnTextIOS: {
    fontSize: fontSize.h6,
    textAlign: 'center',
    color: colors.disabledBg2,
    borderColor: colors.black,
  },
  interestOption: {marginTop: sizes.screenHeight * 0.025},
  bgImage: {
    height: sizes.screenHeight * 0.09,
    resizeMode: 'cover',
    width: sizes.screenWidth,
    marginBottom: sizes.screenHeight * -0.04,
  },
});
