import {Dimensions, StyleSheet} from 'react-native';
import {colors, fontFamily, fontSize, sizes} from '../../services';

export const styles = StyleSheet.create({
  container: {
    height: sizes.screenHeight,
    backgroundColor: colors.white,
    // justifyContent: 'space-between',
  },
  label: {
    color: colors.black,
    fontSize: fontSize.medium,
    marginLeft: sizes.screenWidth * 0.03,
    marginBottom: sizes.screenHeight * 0.01,
    fontWeight: '500',
  },
  input: {
    backgroundColor: colors.white,
    width: sizes.screenWidth * 0.8,
    borderRadius: sizes.screenWidth * 0.5,
    alignSelf: 'center',
    color: colors.black,
    fontSize: fontSize.medium,
    paddingLeft: sizes.screenWidth * 0.05,
    borderWidth: 1,
    borderColor: colors.disabledBg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2.84,
    elevation: 2,
  },
  inputIOS: {
    backgroundColor: colors.white,
    width: sizes.screenWidth * 0.8,
    borderRadius: sizes.screenWidth * 0.5,
    alignSelf: 'center',
    color: colors.black,
    paddingLeft: sizes.screenWidth * 0.05,
    fontSize: fontSize.medium,
    borderWidth: 1,
    borderColor: colors.disabledBg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2.84,
    elevation: 2,
    padding: sizes.screenHeight * 0.02,
  },
  top: {
    marginTop: sizes.screenHeight * 0.05,
  },
  locationView: {
    backgroundColor: colors.appTextColor1,
    padding: sizes.screenHeight * 0.015,
    width: sizes.screenWidth * 0.8,
    alignSelf: 'center',
    borderRadius: sizes.screenWidth * 0.5,
    marginBottom: sizes.screenHeight * 0.02,
    borderWidth: 2,
    borderColor: colors.appTextColor1,
  },
  locationViewGrey: {
    backgroundColor: colors.white,
    padding: sizes.screenHeight * 0.015,
    width: sizes.screenWidth * 0.8,
    alignSelf: 'center',
    borderRadius: sizes.screenWidth * 0.5,
    marginBottom: sizes.screenHeight * 0.023,
    borderWidth: 2,
    borderColor: colors.disabledBg,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  locationText: {
    fontSize: fontSize.h6,
    color: colors.black,
    fontWeight: '500',
    textAlign: 'center',
    alignSelf: 'center',
    right: sizes.screenWidth * 0.03,
    width: sizes.screenWidth * 0.7,
  },
  lcoationIcon: {
    height: sizes.screenHeight * 0.03,
    width: sizes.screenHeight * 0.03,
    left: sizes.screenWidth * 0.05,
  },
  btnView: {
    marginBottom: sizes.screenHeight * 0.06,
  },
  btnViewIOS: {
    marginBottom: sizes.screenHeight * 0.09,
  },
  loader: {
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    padding: sizes.screenHeight * 0.02,
    width: sizes.screenWidth * 0.5,
    borderRadius: sizes.screenWidth * 0.03,
  },
  modalView: {
    backgroundColor: colors.white,
    height: sizes.screenHeight * 0.33,
    width: sizes.screenWidth * 0.7,
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: sizes.screenWidth * 0.06,
    justifyContent: 'center',
  },
  checkmark: {
    height: sizes.screenHeight * 0.04,
    width: sizes.screenHeight * 0.04,
    bottom: sizes.screenHeight * 0.05,
  },
  modelText: {
    fontSize: fontSize.medium,
    textAlign: 'center',
    color: colors.black,
    width: sizes.screenWidth * 0.45,
    fontWeight: '500',
    bottom: sizes.screenHeight * 0.03,
  },
  submitTopModal: {
    bottom: sizes.screenHeight * 0.1,
  },
  signInBtnModal: {
    height: sizes.screenHeight * 0.06,
    width: sizes.screenWidth * 0.4,
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    borderRadius: sizes.screenWidth * 0.02,
  },
  signInBtnModal: {
    height: sizes.screenHeight * 0.06,
    width: sizes.screenWidth * 0.4,
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    borderRadius: sizes.screenWidth * 0.02,
  },
  signUpContent: {
    paddingRight: sizes.screenWidth * 0.05,
    paddingLeft: sizes.screenWidth * 0.05,
  },
  btnTextIOS: {
    textAlign: 'center',
    marginTop: sizes.screenHeight * 0.018,
    color: colors.black,
    fontWeight: '700',
    fontSize: fontSize.medium,
  },
  btnText: {
    textAlign: 'center',
    marginTop: sizes.screenHeight * 0.015,
    color: colors.black,
    fontWeight: '700',
    fontSize: fontSize.medium,
  },
  blueText: {
    color: colors.appTextColor1,
    fontWeight:'800',
  },
});
