import {Dimensions, StyleSheet} from 'react-native';
import {colors, fontFamily, fontSize, sizes} from '../../services';

export const styles = StyleSheet.create({
  container: {
    height: sizes.screenHeight,
    backgroundColor: colors.white,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  logoView: {
    alignSelf: 'center',
  },
  logoImg: {
    width: sizes.screenHeight * 0.4,
    height: sizes.screenHeight * 0.2,
  },
  signinView: {
    width: sizes.screenWidth * 0.85,
    // height: sizes.screenHeight * 0.51,
    paddingBottom: sizes.screenHeight * 0.02,
    backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: 10,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.17,
    shadowRadius: 3.05,
    elevation: 4,
  },
  signinViewIOS: {
    width: sizes.screenWidth * 0.85,
    height: sizes.screenHeight * 0.44,
    backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: sizes.screenWidth * 0.05,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.17,
    shadowRadius: 3.05,
    elevation: 4,
  },
  text1: {
    color: colors.black,
    fontSize: fontSize.extraLarge,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: sizes.screenHeight * 0.02,
  },
  top: {
    marginTop: sizes.screenHeight * 0.02,
  },
  input: {
    backgroundColor: colors.white,
    width: sizes.screenWidth * 0.8,
    borderRadius: sizes.screenWidth * 0.5,
    alignSelf: 'center',
    color: colors.black,
    fontSize: fontSize.medium,
    paddingLeft: sizes.screenWidth * 0.15,
    borderWidth: 1,
    borderColor: colors.disabledBg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2.84,
    elevation: 2,
  },

  inputIOS: {
    backgroundColor: colors.white,
    width: sizes.screenWidth * 0.8,
    borderRadius: sizes.screenWidth * 0.5,
    alignSelf: 'center',
    color: colors.black,
    paddingLeft: sizes.screenWidth * 0.15,
    borderWidth: 1,
    borderColor: colors.disabledBg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2.84,
    elevation: 2,
    padding: sizes.screenHeight * 0.02,
  },
  forgotPassView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: sizes.screenWidth * 0.05,
  },
  checkboxView: {flexDirection: 'row', alignItems: 'center'},
  checkboxTitle: {color: colors.disabledBg2},
  forgotPassText: {
    color: colors.appTextColor1,
    fontWeight: 'bold',
    textDecorationColor: colors.appTextColor1,
    textDecorationLine: 'underline',
    fontSize: fontSize.medium,
  },
  btn: {
    marginTop: sizes.screenHeight * 0.03,
  },
  row: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginTop: sizes.screenHeight * 0.02,
  },
  forgetText: {
    fontSize: fontSize.medium,
    color: colors.black,
  },
  resendText: {
    fontSize: fontSize.medium,
    color: colors.appTextColor1,
    fontWeight: '800',
  },
  btnTop: {
    marginTop: sizes.screenHeight * 0.05,
    marginBottom: sizes.screenHeight * 0.05,
  },
  btnTopIOS: {
    marginTop: sizes.screenHeight * 0.05,
    marginBottom: sizes.screenHeight * 0.1,
    alignSelf:'center'
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: sizes.screenWidth * 0.2,
    paddingLeft: sizes.screenWidth * 0.17,
    marginTop: sizes.screenHeight * 0.02,
  },
  darkBtn: {
    backgroundColor: colors.black,
    padding: sizes.screenHeight * 0.009,
    borderRadius: sizes.screenWidth * 0.3,
    width: sizes.screenWidth * 0.31,
    marginRight: sizes.screenWidth * 0.05,
  },
  row2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: sizes.screenHeight * 0.02,
  },
  fb: {
    height: sizes.screenHeight * 0.03,
    width: sizes.screenHeight * 0.03,
    bottom: sizes.screenHeight * 0.002,
  },
  darkBtnText: {
    textAlign: 'center',
    color: colors.appTextColor1,
    fontSize: fontSize.medium,
  },
  greenBtn: {
    backgroundColor: colors.appTextColor1,
    padding: sizes.screenHeight * 0.009,
    borderRadius: sizes.screenWidth * 0.3,
    width: sizes.screenWidth * 0.31,
  },
  google: {
    height: sizes.screenHeight * 0.03,
    width: sizes.screenHeight * 0.04,
    right: sizes.screenWidth * 0.01,
    // left: sizes.screenWidth * 0.0,
  },
  greenBtnText: {
    textAlign: 'center',
    color: colors.black,
    fontSize: fontSize.medium,
    left: sizes.screenWidth * 0.02,
  },
  googleRight: {
    textAlign: 'center',
    color: colors.black,
    fontSize: fontSize.medium,
  },
  errorText: {
    color: colors.error,
    fontSize: fontSize.smallM,
    paddingLeft: sizes.screenWidth * 0.04,
    marginBottom:sizes.screenHeight * 0.01
  },
  loader: {
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    padding: sizes.screenHeight * 0.02,
    width: sizes.screenWidth * 0.5,
    borderRadius: sizes.screenWidth * 0.03,
  },
  inputView: {
    flexDirection: 'row',
    marginBottom: sizes.screenHeight * 0.035,
    alignItems: 'center',
    paddingHorizontal: sizes.screenWidth * 0.03,
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    width: sizes.screenWidth * 0.8,
    borderRadius: sizes.screenWidth * 0.5,
    alignSelf: 'center',
    color: colors.black,
    fontSize: fontSize.medium,
    borderWidth: 1,
    borderColor: colors.disabledBg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2.84,
    elevation: 2,
  },
  input2: {
    width: sizes.screenWidth * 0.6,
    paddingLeft: sizes.screenWidth * 0.05,
    color: colors.black,
  },
  input2IOS: {
    padding: sizes.screenHeight * 0.02,
    paddingLeft: sizes.screenWidth * 0.06,
    width: sizes.screenWidth * 0.6,
  },
  showPassTouchable: {
    padding: sizes.screenWidth * 0.01,
  },
  bgImage: {
    height: sizes.screenHeight * 0.16,
    resizeMode:'cover',
    width: sizes.screenWidth,
    marginBottom:sizes.screenHeight * 0.04
  },
});
