import {Dimensions, StyleSheet} from 'react-native';
import {colors, fontFamily, fontSize, sizes} from '../../services';

export const styles = StyleSheet.create({
  container: {backgroundColor: colors.white},
  backgrouondImg: {
    width: sizes.screenWidth,
    height: sizes.screenHeight * 0.3,
  },
  profileImg: {
    width: sizes.screenWidth * 0.4,
    height: sizes.screenWidth * 0.4,
    alignSelf: 'center',
    borderColor: colors.white,
    borderWidth: sizes.screenWidth * 0.015,
    borderRadius: sizes.screenWidth * 0.3,
  },
  uploadImgBtn: {
    width: sizes.screenWidth * 0.12,
    height: sizes.screenWidth * 0.12,
    borderRadius: sizes.screenWidth * 0.3,
  },
  uploadImgTouchable: {
    width: sizes.screenWidth * 0.12,
    height: sizes.screenWidth * 0.12,
    position: 'absolute',
    right: 0,
    bottom: 4,
    borderRadius: sizes.screenWidth * 0.3,
  },
  imgView: {
    width: sizes.screenWidth * 0.4,
    height: sizes.screenWidth * 0.4,
    borderRadius: sizes.screenWidth * 0.3,
    top: sizes.screenHeight * 0.075,
    alignSelf: 'center',
  },
  text1: {
    color: colors.disabledBg2,
    marginTop: sizes.screenHeight * 0.12,
    marginLeft: sizes.screenWidth * 0.14,
  },
  input: {
    backgroundColor: 'transparent',
    width: sizes.screenWidth * 0.8,
    height: sizes.screenHeight * 0.06,
    alignSelf: 'center',
    borderColor: colors.grayBorder,
    borderWidth: 1,
    color: colors.black,
    borderRadius: sizes.screenWidth * 0.06,
    paddingLeft: sizes.screenWidth * 0.05,
    fontSize: fontSize.h6,
  },
  inputDisable: {
    backgroundColor: 'transparent',
    width: sizes.screenWidth * 0.8,
    height: sizes.screenHeight * 0.06,
    alignSelf: 'center',
    borderColor: colors.grayBorder,
    borderWidth: 1,
    color: colors.disabledBg2,
    borderRadius: sizes.screenWidth * 0.06,
    paddingLeft: sizes.screenWidth * 0.05,
    fontSize: fontSize.h6,
  },
  text2: {
    color: colors.disabledBg2,
    marginTop: sizes.screenHeight * 0.02,
    marginLeft: sizes.screenWidth * 0.14,
  },
  dropDown: {
    backgroundColor: colors.white,
    padding: sizes.screenHeight * 0.015,
    width: sizes.screenWidth * 0.8,
    alignSelf: 'center',
    borderRadius: sizes.screenWidth * 0.5,
    borderColor: colors.grayBorder,
    borderWidth: 1,
    height: sizes.screenHeight * 0.06,
  },
  dropItem: {
    fontSize: fontSize.h6,
    color: colors.black,
    fontWeight: 'bold',
    marginLeft: sizes.screenWidth * 0.03,
    textAlign: 'center',
  },
  btn: {
    marginTop: sizes.screenHeight * 0.03,
    marginBottom: sizes.screenHeight * 0.02,
  },
  loader: {
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    padding: sizes.screenHeight * 0.02,
    width: sizes.screenWidth * 0.5,
    borderRadius: sizes.screenWidth * 0.03,
  },
  modalView: {
    backgroundColor: colors.white,
    height: sizes.screenHeight * 0.33,
    width: sizes.screenWidth * 0.7,
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: sizes.screenWidth * 0.06,
    justifyContent: 'center',
  },
  checkmark: {
    height: sizes.screenHeight * 0.04,
    width: sizes.screenHeight * 0.04,
    bottom: sizes.screenHeight * 0.05,
  },
  modelText: {
    fontSize: fontSize.medium,
    textAlign: 'center',
    color: colors.black,
    width: sizes.screenWidth * 0.4,
    fontWeight: '500',
    bottom: sizes.screenHeight * 0.03,
  },
  submitTopModal: {
    bottom: sizes.screenHeight * 0.1,
  },
  signInBtnModal: {
    height: sizes.screenHeight * 0.06,
    width: sizes.screenWidth * 0.4,
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    borderRadius: sizes.screenWidth * 0.02,
  },
  signInBtnModal: {
    height: sizes.screenHeight * 0.06,
    width: sizes.screenWidth * 0.4,
    alignSelf: 'center',
    backgroundColor: colors.appTextColor1,
    borderRadius: sizes.screenWidth * 0.02,
  },
  signUpContent: {
    paddingRight: sizes.screenWidth * 0.05,
    paddingLeft: sizes.screenWidth * 0.05,
  },
  btnTextIOS: {
    textAlign: 'center',
    marginTop: sizes.screenHeight * 0.018,
    color: colors.black,
    fontWeight: '700',
    fontSize: fontSize.medium,
  },
  btnText: {
    textAlign: 'center',
    marginTop: sizes.screenHeight * 0.015,
    color: colors.black,
    fontWeight: '700',
    fontSize: fontSize.medium,
  },
  blueText: {
    color: colors.appTextColor1,
    fontWeight: '800',
  },
  ratingInputIOS: {
    height: sizes.screenHeight * 0.45,
    textAlignVertical: 'top',
    width: sizes.screenWidth * 0.8,
    borderRadius: sizes.screenWidth * 0.05,
    padding: sizes.screenWidth * 0.06,
    color: colors.black,
    fontSize: fontSize.h6,
    backgroundColor: colors.grayBg,
    paddingTop: sizes.screenHeight * 0.02,
  },
  ratingInput: {
    height: sizes.screenHeight * 0.16,
    alignSelf: 'center',
    textAlignVertical: 'top',
    width: sizes.screenWidth * 0.8,
    borderRadius: sizes.screenWidth * 0.05,
    paddingHorizontal: sizes.screenWidth * 0.05,
    color: colors.black,
    fontSize: fontSize.h6,
    backgroundColor: colors.white,
    borderColor: colors.grayBg,
    borderWidth: 1,
  },
});
